export const likes = [
  "sri lanka",
  "jamaica",
  "ghana",
  "croatia",
  "italy",
  "greece",
  "my boyfriend",
  "redux",
  "react",
  "garlic",
  "coriander",
  "cyprus",
  "edinburgh",
  "prague",
  "morocco",
  "belgium",
  "driving",
  "indie rock",
  "the killers",
  "coldplay",
  "kid bloom",
  "buffalo hot sauce",
  "the phoenix project",
  "marvel movies",
  "deliveroo",
  "oxford",
  "longchamp",
  "tk maxx",
  "flares",
  "github",
  "reddit",
  "collecting things",
  "mexican food",
  "all asian food",
  "sting rays",
  "aquariums",
  "nachos",
  "gin",
  "bali",
  "intelliJ",
  "family",
  "memes",
  "macbook",
  "golden spaniels",
  "retrievers",
  "old english sheepdogs",
  "south africa",
  "finland",
  "skiing",
  "paris",
  "seaside towns",
  "oysters",
  "white bait",
  "crisps",
  "studio ghibli",
  "spotify",
  "sudoku",
  "google drive",
  "citymapper",
  "waterparks",
  "wine tasting",
  "hamilton russell vineyard",
  "snorkelling",
  "scrapbooking",
  "nights out in brixton",
  "ducksoup soho",
  "ottolenghi",
  "the school of life",
  "sprite",
  "lime soda",
  "chile",
  "pebre",
  "houmous",
  "taramasalata",
  "peanut butter",
  "silicon valley",
  "the it crowd",
  "rick and morty",
  "white oleander",
  "pukka nighttime tea",
  "capers",
  "tapas",
  "tacos",
  "peonies",
  "marks and spencer",
  "sainsburys",
  "candles",
  "bristol",
  "national trust houses",
  "cookbooks",
  "aerosmith",
  "marion cotillard",
  "the good wife",
  "josh charles",
  "blue cheese",
  "mercato metropolitano",
  "killing eve",
  "dirtbag",
  "deadpool",
  "taron egerton",
  "somerset",
  "lemons",
  "empanadas",
  "champagne coupes",
  "hamilton",
  "vance joy",
  "arctic monkeys",
  "kasabian",
  "rainbow kitten surprise",
  "the flight club"
];
